#!/bin/bash -e
## Install dependencies
/usr/bin/r10k puppetfile install

## Run Puppet locally using puppet apply
/usr/bin/puppet apply /etc/puppet/manifests/site.pp \
  --modulepath=modules:thirdparty

## Log status of the Puppet run
if [ $? -eq 0 ]
then
  /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
  exit 0
else
  /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
  exit 1
fi
